### ISSUE TITLE
Fastlane lacking changelog for last release

### ISSUE THREAD

**Issue by IzzySoft** [thoughtsunificator/domodel-diary-android#1]
No complaint, just in case this might have slipped through: there's no `2.txt` in Fastlane's `changelog/` directory. Would be great if you could include those per-release changelogs :wink: Thanks!

**Comment by thoughtsunificator** [comment]
You're right. I've added it and I've also tagged the release.

**Comment by IzzySoft** [comment]
Thanks! How comes I already have v1.2 here from 4 days ago, and your newest tag, created half an hour ago, is also 1.2? Should't that be 1.3 – and now we miss a `3.txt` (according to the `build.gradle` behind the tag)? :thinking:

**Comment by thoughtsunificator** [comment]
You can safely dismiss the 1.2. I've added 3.txt. Thanks!

**Comment by IzzySoft** [comment]
Thanks! That worked out. I've just triggered the updater manually, and it grabbed the APK and the `3.txt`.
